# #azure-pipeline.yml

# trigger: none

# pool:
#   myagent

# extends:
#   template: testing-template.yml
#   parameters:
#     testSet:
#     - job: positive_test
#       templateContext:
#         expectedHTTPResponseCode: 200
#       steps:
#       - script: echo "Run positive test" 
#     - job: negative_test
#       templateContext:
#         expectedHTTPResponseCode: 501
#       steps:
#       - script: echo "Run negative test"

# File: azure-pipelines.yml
# trigger: none
# pool:
#   myagent

# extends:
#   template: simple-param.yml
#   parameters:
#       yesNo: true # set to a non-boolean value to have the build fail




trigger: none

resources:
 repositories:
   - repository: test_template
     type: github
     name: abhishektiwari-knoldus/pipeline-terrafrom-integration
     ref: 'ok_report'
     endpoint: 'Abhishek'

stages:
- stage: deploy_dev 
  jobs:
  - template: webapp-template.yml@test_template
    parameters:
      environment: 'dev'
      appName: 'dev_Wala'
      agent: 'myagent'

- stage: deploy_staging
  jobs:
  - template: webapp-template.yml
    parameters:
      environment: 'staging'
      appName: 'Staging_Wala'

- stage: deploy_production
  jobs:
  - template: webapp-template.yml
    parameters:
      environment: 'production'
      appName: 'Prod_Wala'
