# webapp-template.yml

parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'staging'
    - 'production'

- name: appName
  displayName: 'Application Name'
  type: string

jobs:
- job: build_and_deploy
  displayName: 'Build and Deploy'
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      echo "Building and deploying ${{ parameters.appName }} to ${{ parameters.environment }}"
      # Add your build and deployment steps here
    displayName: 'Build and Deploy'
